FROM sciruby/iruby-notebook
USER root
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y sqlite3
RUN apt-get install -y libsqlite3-dev
RUN apt-get install -y graphviz
RUN gem install sequel
RUN gem install descriptive_statistics
RUN gem install sqlite3 
RUN gem install daru
RUN gem install kmeans-clusterer
RUN gem install rgl
RUN gem install redis
