version: '3'
services:
  notebook:
    build: .
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ./sciruby/:/home/jovyan/work/
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data    
